FROM m.daocloud.io/docker.io/library/python:3.9-slim
WORKDIR /app
# 复制依赖清单并安装
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
# 复制所有代码和证书
COPY . .
# 声明网关使用的 HTTPS 端口
EXPOSE 443
CMD ["python", "app.py"]
